[server]
maxUploadSize=2048

[theme]

base = "light"

primaryColor = '#7792E3'


backgroundColor = '#273346'


secondaryBackgroundColor = "black"  #'#B9F1C0'


textColor = "white"


font = "sans serif"